### ISSUE TITLE
Error while opening some pages.

### ISSUE THREAD

**Issue by LiquidatorCoder** [anki2jain/boxoffice#1]
The app gives error while opening some movie information pages and also while searching for a movie.  
![Screenshot_2020-02-03-10-03-50-523_com example lastapp](https://user-images.githubusercontent.com/42910433/73626035-5fbfb400-466d-11ea-84c1-83db2504b4fe.jpg)
![Screenshot_2020-02-03-10-04-23-914_com example lastapp](https://user-images.githubusercontent.com/42910433/73626036-60584a80-466d-11ea-9d7c-f21a56dd0740.jpg)

 Btw, Great App!👍🏻👍🏻

**Comment by anki2jain** [comment]
Ya there is some missing null checks btw this was  my first flutter.

**Comment by anki2jain** [comment]
Ya there are some missing null checks.
